channels:
  - conda-forge
  - fastai
  - pytorch
  - defaults
dependencies:
  - appmode
  - jupyter
  - pytorch>=1.3.0
  - torchvision>=0.5
  - matplotlib
  - pandas
  - requests
  - pyyaml
  - fastprogress>=0.1.22
  - python>=3.6
  - pip
  - scikit-learn
  - scipy
  - spacy
  - ipywidgets>=7.5.1
  - fastai=1.0.60 
  - pillow>=7.0.0
  - packaging
  - pip:
    - fastai2
    - nvidia-ml-py3
