channels:
  - conda-forge
  - fastai
  - pytorch
  - defaults
dependencies:
  - appmode
  - jupyter
  - pytorch>=1.3.0
  - torchvision>=0.5
  - matplotlib
  - pandas
  - requests
  - pyyaml
  - fastprogress>=0.1.22
  - pillow
  - python>=3.6
  - pip
  - scikit-learn
  - scipy
  - spacy
  - ipywidgets>=7.5.1
